name: Docker image push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read and set version
        id: set-version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Build docker image with specific version
        run: |
          echo "${{ env.VERSION }}"
          docker build . --file Dockerfile --tag ronnie1993/myserver:${{ env.VERSION }}
      - name: Tag docker with latest keyword
        run: docker tag ronnie1993/myserver:${{ env.VERSION }} ronnie1993/myserver:latest
      - name: Login to DockerHHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker image with version
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags:  ronnie1993/myserver:${{ env.VERSION }}, ronnie1993/myserver:latest
      
