name: Docker image push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.set-version.outputs.version}}
    steps:
      - uses: actions/checkout@v4
      - name: Read and set version
        id: set-version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Build docker image with specific version
        run: |
          echo "${{ env.VERSION }}"
          docker build . --file Dockerfile --tag ronnie1993/myserver:${{ env.VERSION }}
      - name: Tag docker with latest keyword
        run: docker tag ronnie1993/myserver:${{ env.VERSION }} ronnie1993/myserver:latest

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: print version
        run: echo "${{ needs.build.outputs.version }}"
      - name: Login to DockerHHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker image with version
        run: docker push ronnie1993/myserver:${{ needs.build.outputs.version }}
      - name: Push docker image with latest tag
        run: docker push ronnie1993/myserver:latest
      
